# basic feedforward neural network
fnn:
  # parameters
  learning_rate: 0.1
  num_steps: 500
  batch_size: 128
  epoch: 3
  display_step: 100

  # network paras
  layers: [784, 256, 256]
  num_input: 784 # MNIST data input (img shape: 28*28)
  n_hidden_1: 256 # 1st layer number of neurons
  n_hidden_2: 256 # 2nd layer number of neurons
  num_classes: 10 # MNIST total classes (0-9 digits)

# convolution neural network
cnn:

# long short term memory
lstm:

# bidirectional lstm
bilstm:

# gated recurrent unit
gru:

in:
  data_path: ../data/ubiquant-market-prediction

out:
  model_path: ../out
  dump_path: ../out